const texts = {
"spanish": 
    { "shortDescription" : "Marmotas dreams es un proyecto que se desarrolla en el diálogo entre la música experimental y las artes visuales producidas con código. Una experiencia poética, una cacería conjunta hacia el corazón y el significado de las cosas y los lenguajes. Experimentamos con las estructuras significantes de la música, el arte sonoro, el lenguaje computacional y la performance vocal y fonética de textos poéticos en distintas lenguas. Componemos obras en procesos de retroalimentación entre el arte sonoro, la poesía, la música experimental y electrónica, la performance, la improvisación, la instalación y la programación en vivo.",
        "longDescription":"Marmotas Dreams es un dúo de experimentación sonora conformado por Berenice Llorens y Constanza Pellicci en sus inicios. El dúo desarrolla obras y canciones desde la improvisación, buscando habitar y expandir la frontera de lo ya escuchado; generando un diálogo entre estéticas convencionales y estructuras compositivas más libres. <div style=\"font-style:italic\">‘Apuntamos a alimentar extrañezas y sutiles desplazamientos que den lugar a la diversidad de géneros, poéticas y estéticas en tiempo de producciones estandarizadas por la industria musical’.</div><br> Desde 2017, Marmotas Dreams propone investigar  maneras de expandir la estructura y la forma de la canción, para construir otras narrativas y estructuras compositivas más  próximas a la deriva, que a la repetición de materiales conocidos e identificables. El dúo trabaja con voces y técnicas de canto ampliadas, sintetizadores, grabaciones de campo, guitarras y procesos. <br><br> Desde 2018 realizan conciertos y performances. En 2020 graban su primer material discográfico ‘Pequeño kimono’ con el cual inician un proyecto compositivo llamado Voyage. Este proyecto propone explorar maneras de viajar a través de sonidos por diferentes paisajes geográficos, experimentando con diversas lenguas, fonéticas y sonoridades.<br><br> En 2021 inician un segundo proyecto compositivo que conformará el disco ‘Leaving Leaves’ (editado por La mona de Oro records). Tres piezas compuestas a partir de una selección de poemas del libro ‘Leaves of grass’ de Walt Whitman, sobre bases electrónicas y procesos en mixtura con instrumentos analógicos y digitales. A partir de este proyecto inician una colaboración con la artista digital y live coder Karen Palacio, con quien realizan la pieza audiovisual, Respiration, como así también una serie de conciertos con visuales de live coding en vivo. Desde entonces conforman un trío centrado en el desarrollo y despliegue del proyecto ‘Leaving Leaves’ para el cual cuentan con una beca creación del Fondo Nacional de las Artes y con el que participan de conciertos en centros de arte sonoro, salas de conciertos de música experimental, media labs y festivales internacionales de música experimental y realizaciones audiovisuales."
    },
"english": 
    { "shortDescription" : "Marmotas dreams is a project of experimental music and visual art produced with livecoding. A poetic experience, a joint hunt into the heart and meaning of things and the language. We experiment with the significant structures of music, sound art, computer language and the vocal and phonetic performance of poetic texts in different languages. We compose works in feedback processes between sound art, poetry, experimental and electronic music, performance, improvisation, installation and live programming.",
    "longDescription" :'asd "asd"',
    },
}
